# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendSlackReminderJob`.
# Please instead update this file by running `bin/tapioca dsl SendSlackReminderJob`.


class SendSlackReminderJob
  class << self
    sig do
      params(
        args: T.untyped,
        block: T.nilable(T.proc.params(job: SendSlackReminderJob).void)
      ).returns(T.any(SendSlackReminderJob, FalseClass))
    end
    def perform_later(*args, &block); end

    sig { params(args: T.untyped).returns(T.untyped) }
    def perform_now(*args); end
  end
end
