/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates a user account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["create_user_request"];
        };
      };
      responses: {
        /** @description user created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["user_response"];
          };
        };
        /** @description invalid user params */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["validation_error_response"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logs in a user to their account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["login_user_request"];
        };
      };
      responses: {
        /** @description logged in successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["user_response"];
          };
        };
        /** @description invalid login credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["user_devise_invalid_login_response"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Logs out a user from their active authenticated session */
    delete: {
      parameters: {
        query?: never;
        header: {
          Cookie: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description logged out user successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["generic_success_response"];
          };
        };
        /** @description invalid active session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["generic_error_response"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetches user information for current authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description fetched user successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["user_response"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Generic success response body */
    generic_success_response: {
      /** @description Shared status metadata returned by API responses. */
      status: {
        message: string;
      };
      /**
       * @description No resource payload is returned for this response
       * @example null
       */
      data: unknown;
    };
    /** @description Generic error response body */
    generic_error_response: {
      /** @description Shared status metadata returned by API responses. */
      status: {
        message: string;
      };
      errors: {
        field: string;
        message: string;
      }[];
    };
    /** @description Shared status metadata returned by API responses. */
    status: {
      message: string;
    };
    /** @description Public user account data returned by the API. */
    user: {
      id: number;
      /** Format: email */
      email: string;
      first_name: string;
      last_name: string;
    };
    /** @description Full response body for endpoints that return one user. */
    user_response: {
      /** @description Shared status metadata returned by API responses. */
      status: {
        message: string;
      };
      data: {
        /** @description Public user account data returned by the API. */
        user: {
          id: number;
          /** Format: email */
          email: string;
          first_name: string;
          last_name: string;
        };
      };
    };
    /** @description Full response body for invalid login request */
    user_devise_invalid_login_response: {
      /**
       * @description Devise authentication error message
       * @example Invalid Email or password.
       */
      error: string;
    };
    /** @description Request body for creating a new user account */
    create_user_request: {
      user: {
        /** Format: email */
        email: string;
        first_name: string;
        last_name: string;
        /** Format: password */
        password: string;
        /** Format: password */
        password_confirmation: string;
      };
    };
    /** @description Request body for logging in to a user account. */
    login_user_request: {
      /** @description Credentials for the user account being authenticated. */
      user: {
        /** Format: email */
        email: string;
        /** Format: password */
        password: string;
      };
    };
    /** @description One individual error detail, usually used inside an errors array. */
    error: {
      field: string;
      message: string;
    };
    /** @description Full response body for a generic API error without field-level details. */
    error_response: {
      /** @description Shared status metadata returned by API responses. */
      status: {
        message: string;
      };
    };
    /** @description Full response body for validation errors with field-level details. */
    validation_error_response: {
      /** @description Shared status metadata returned by API responses. */
      status: {
        message: string;
      };
      errors: {
        field: string;
        message: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
