# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-auto_inject` gem.
# Please instead update this file by running `bin/tapioca gem dry-auto_inject`.


# pkg:gem/dry-auto_inject#lib/dry/auto_inject.rb:6
module Dry
  class << self
    # Configure an auto-injection module
    #
    # @example
    #    module MyApp
    #      # set up your container
    #      container = Dry::Core::Container.new
    #
    #      container.register(:data_store, -> { DataStore.new })
    #      container.register(:user_repository, -> { container[:data_store][:users] })
    #      container.register(:persist_user, -> { PersistUser.new })
    #
    #      # set up your auto-injection function
    #      AutoInject = Dry::AutoInject(container)
    #
    #      # define your injection function
    #      def self.Inject(*keys)
    #        AutoInject[*keys]
    #      end
    #    end
    #
    #    # then simply include it in your class providing which dependencies should be
    #    # injected automatically from the configured container
    #    class PersistUser
    #      include MyApp::Inject(:user_repository)
    #
    #      def call(user)
    #        user_repository << user
    #      end
    #    end
    #
    #    persist_user = container[:persist_user]
    #
    #    persist_user.call(name: 'Jane')
    #
    # @return [Proc] calling the returned proc builds an auto-injection module
    #
    # @api public
    #
    # pkg:gem/dry-auto_inject#lib/dry/auto_inject.rb:62
    def AutoInject(container, options = T.unsafe(nil)); end
  end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject.rb:7
module Dry::AutoInject
  class << self
    # pkg:gem/dry-auto_inject#lib/dry/auto_inject.rb:8
    def loader; end
  end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:5
class Dry::AutoInject::Builder
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:15
  def initialize(container, options = T.unsafe(nil)); end

  # @api public
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:21
  def [](*dependency_names); end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:7
  def container; end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:10
  def strategies; end

  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:27
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/builder.rb:23
  def respond_to_missing?(name, _ = T.unsafe(nil)); end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:10
class Dry::AutoInject::DependencyMap
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:11
  def initialize(*dependencies); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:27
  def inspect; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:29
  def names; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:33
  def to_h; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:34
  def to_hash; end

  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:48
  def add_dependency(name, identifier); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:38
  def name_for(identifier); end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:6
class Dry::AutoInject::DependencyNameInvalid < ::StandardError; end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:5
class Dry::AutoInject::DuplicateDependencyError < ::StandardError; end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:7
class Dry::AutoInject::Injector < ::BasicObject
  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:20
  def initialize(container, strategy, builder:); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:26
  def [](*dependency_names); end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:15
  def builder; end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:9
  def container; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:17
  def respond_to?(*_arg0); end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:12
  def strategy; end

  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:32
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/injector.rb:28
  def respond_to_missing?(name, _ = T.unsafe(nil)); end
end

# @api private
#
# pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:6
class Dry::AutoInject::MethodParameters
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:25
  def initialize(parameters); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:51
  def empty?; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:49
  def keyword?(name); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:43
  def keyword_names; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:53
  def length; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:23
  def parameters; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:55
  def pass_through?; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:35
  def sequential_arguments?; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:29
  def splat?; end

  class << self
    # pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:7
    def of(obj, name); end
  end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/method_parameters.rb:73
Dry::AutoInject::MethodParameters::EMPTY = T.let(T.unsafe(nil), Dry::AutoInject::MethodParameters)

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies.rb:5
class Dry::AutoInject::Strategies
  extend ::Dry::Core::Container::Mixin
  extend ::Dry::Core::Container::Configuration
  extend ::Dry::Core::Constants
  extend ::Dry::Configurable
  extend ::Dry::Configurable::Methods
  extend ::Dry::Configurable::ClassMethods

  class << self
    # @api public
    #
    # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies.rb:9
    def register_default(name, strategy); end
  end
end

# @api private
#
# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/args.rb:7
class Dry::AutoInject::Strategies::Args < ::Dry::AutoInject::Strategies::Constructor
  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/args.rb:24
  def define_initialize(klass); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/args.rb:37
  def define_initialize_with_params; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/args.rb:50
  def define_initialize_with_splat(super_parameters); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/args.rb:10
  def define_new; end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:6
class Dry::AutoInject::Strategies::Constructor < ::Module
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:15
  def initialize(container, *dependency_names); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:13
  def class_mod; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:10
  def container; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:11
  def dependency_map; end

  # @api private
  #
  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:24
  def included(klass); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:12
  def instance_mod; end

  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:50
  def define_initialize(_klass); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:46
  def define_new; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:38
  def define_readers; end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:7
class Dry::AutoInject::Strategies::Constructor::ClassMethods < ::Module; end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/constructor.rb:8
class Dry::AutoInject::Strategies::Constructor::InstanceMethods < ::Module; end

# @api private
#
# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/hash.rb:7
class Dry::AutoInject::Strategies::Hash < ::Dry::AutoInject::Strategies::Constructor
  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/hash.rb:24
  def define_initialize(klass); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/hash.rb:10
  def define_new; end
end

# @api private
#
# pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:7
class Dry::AutoInject::Strategies::Kwargs < ::Dry::AutoInject::Strategies::Constructor
  private

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:88
  def assign_dependencies(kwargs, destination); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:24
  def define_initialize(klass); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:43
  def define_initialize_with_keywords(super_parameters); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:64
  def define_initialize_with_splat(super_parameters); end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:10
  def define_new; end

  # pkg:gem/dry-auto_inject#lib/dry/auto_inject/strategies/kwargs.rb:99
  def slice_kwargs(kwargs, super_parameters); end
end

# pkg:gem/dry-auto_inject#lib/dry/auto_inject/dependency_map.rb:8
Dry::AutoInject::VALID_NAME = T.let(T.unsafe(nil), Regexp)
