# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-mashify` gem.
# Please instead update this file by running `bin/tapioca gem faraday-mashify`.


# pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:3
module Faraday; end

# This will be your middleware main module, though the actual middleware implementation will go
# into Faraday::Mashify::Middleware for the correct namespacing.
#
# pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:4
module Faraday::Mashify; end

# Public: Converts parsed response bodies to a Hashie::Mash if they were of Hash or Array type.
#
# pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:6
class Faraday::Mashify::Middleware < ::Faraday::Middleware
  # @param app [Proc]
  # @param options [Hash]
  # @option options [Class] :mash_class Responses are wrapped in this class (default is `::Hashie::Mash`)
  #
  # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:20
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # @!attribute [rw] mash_class
  #   @return [Class]
  #
  # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:9
  def mash_class; end

  # @!attribute [rw] mash_class
  #   @return [Class]
  #
  # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:9
  def mash_class=(_arg0); end

  # This method will be called when the response is being processed.
  # You can alter it as you like, accessing things like response_body, response_headers, and more.
  # Refer to Faraday::Env for a list of accessible fields:
  # https://github.com/lostisland/faraday/blob/main/lib/faraday/options/env.rb
  #
  # @param env [Faraday::Env] the environment of the response being processed.
  #
  # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:31
  def on_complete(env); end

  private

  # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:37
  def parse(body); end

  class << self
    # @!attribute [rw] mash_class
    #   @return [Class]
    #
    # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:14
    def mash_class; end

    # @!attribute [rw] mash_class
    #   @return [Class]
    #
    # pkg:gem/faraday-mashify#lib/faraday/mashify/middleware.rb:14
    def mash_class=(_arg0); end
  end
end

# pkg:gem/faraday-mashify#lib/faraday/mashify/version.rb:5
Faraday::Mashify::VERSION = T.let(T.unsafe(nil), String)
