# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-google-oauth2` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-google-oauth2`.


# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:8
module OmniAuth; end

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:9
module OmniAuth::Strategies; end

# Main class for Google OAuth2 strategy.
#
# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:11
class OmniAuth::Strategies::GoogleOauth2 < ::OmniAuth::Strategies::OAuth2
  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:31
  def authorize_params; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:99
  def build_access_token; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:92
  def custom_build_access_token; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:88
  def raw_info; end

  private

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:107
  def callback_url; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:139
  def client_get_token(verifier, redirect_uri); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:111
  def get_access_token(request); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:147
  def get_scope(params); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:158
  def get_token_options(redirect_uri = T.unsafe(nil)); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:143
  def get_token_params; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:193
  def image_params; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:189
  def image_size_opts_passed?; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:169
  def image_url; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:103
  def nil_or_empty?(obj); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:162
  def prune!(hash); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:208
  def strip_unnecessary_query_parameters(query_parameters); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:222
  def token_info(access_token); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:154
  def verified_email; end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:239
  def verify_hd(access_token); end

  # pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:232
  def verify_token(access_token); end
end

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:12
OmniAuth::Strategies::GoogleOauth2::ALLOWED_ISSUERS = T.let(T.unsafe(nil), Array)

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:17
OmniAuth::Strategies::GoogleOauth2::AUTHORIZE_OPTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:14
OmniAuth::Strategies::GoogleOauth2::BASE_SCOPES = T.let(T.unsafe(nil), Array)

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:13
OmniAuth::Strategies::GoogleOauth2::BASE_SCOPE_URL = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:15
OmniAuth::Strategies::GoogleOauth2::DEFAULT_SCOPE = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-google-oauth2#lib/omniauth/strategies/google_oauth2.rb:16
OmniAuth::Strategies::GoogleOauth2::USER_INFO_URL = T.let(T.unsafe(nil), String)
